### ISSUE TITLE
`inlayHints` too slow (10 seconds for 10 lines)

### ISSUE THREAD

**Issue by Krutoy242** [raylras/zenscript-intelli-sense#115]
Inlay hints generated when I open /edit document but its too slow.

My file content:
```zs
#norun

val arr = [
  <forestry:fruits:0>,
  <forestry:fruits:1>,
  <forestry:fruits:2>,
  <forestry:fruits:3>,
  <forestry:fruits:4>,
  <forestry:fruits:5>,
  <forestry:fruits:6>,
  <forestry:fruits:7>,
  <forestry:fruits:8>,
  <forestry:fruits:9>,
  <forestry:fruits:10>,
];
```

Extension output:
```less
2024-01-24 13:02:38.131 [INFO] ZenLanguageService - inlayHint ~test2.zs finished 10037 ms
```

![image](https://github.com/raylras/zenscript-intelli-sense/assets/936618/cd817918-6b8d-424b-ad45-c6a932033ef9)

In other files with more captures it could take 2 minutes:
```
inlayHint ~test.zs finished 180004 ms
```

This is way faster on `v0.27.0`

**Comment by raylras** [comment]
It should have been resolved since v0.29.0

**Comment by Krutoy242** [comment]
I installed `v0.29.0` but as fast as i load .zs file i see this error:
![image](https://github.com/raylras/zenscript-intelli-sense/assets/936618/aca0a22e-e76b-4d8c-a946-2bc4af4ecfe3)

And this log in tasks:
```less
Starting ZensScript language server
Launch command: " -Dfile.encoding=UTF-8 -classpath c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\server\* raylras.zen.lsp.StandardIOLauncher"
[Error - 4:50:27 PM] ZenScript Language Client client: couldn't create connection to server.
Error: Unsupported server configuration {
    "command": "",
    "args": [
        "-Dfile.encoding=UTF-8",
        "-classpath",
        "c:\\Users\\LD\\.vscode\\extensions\\raylras.zenscript-intelli-sense-0.29.0\\server\\*",
        "raylras.zen.lsp.StandardIOLauncher"
    ],
    "options": {}
}
	at c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\client\out\extension.js:1:351942
	at async k.createConnection (c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\client\out\extension.js:1:306155)
	at async k.start (c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\client\out\extension.js:1:296549)
	at async c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\client\out\extension.js:1:374947
	at async exports.activate (c:\Users\LD\.vscode\extensions\raylras.zenscript-intelli-sense-0.29.0\client\out\extension.js:1:374218)
	at async u.n (c:\Users\LD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6255)
	at async u.m (c:\Users\LD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6218)
	at async u.l (c:\Users\LD\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:5675)

```

**Comment by Krutoy242** [comment]
Yes, now works way faster! 10-20ms!
